name: Tests

on:
  push:
    branches: ["3.x"]
  pull_request:
    branches: ["3.x"]

permissions:
  contents: read

jobs:
  test:
    name: Test codebase
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["8.5"]
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: bcmath, ctype, dom, json, libxml, mbstring, phar, tokenizer, xml, xmlwriter
          tools: composer:v2
          coverage: none

      - name: Check out repository
        uses: actions/checkout@v6

      - name: Validate configuration
        run: composer validate --strict

      - name: Install dependencies
        run: |
          composer install --no-interaction --optimize-autoloader
          npm ci

      - name: Check formatting
        run: |
          composer run check
          npm run check

      - name: Lint codebase
        run: composer run lint

      - name: Run static analysis
        run: composer run analyze

      - name: Run unit- & integration-tests
        run: composer run test
