name: Test

on:
  push:
    branches: [ "2.x", "3.x" ]
  pull_request:
    branches: [ "2.x", "3.x" ]

permissions:
  contents: read

jobs:
  test:
    name:    Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Validate
        run:  composer validate --strict
      - name: Build
        run:  composer install --prefer-dist --no-progress
      - name: PHPStan
        run:  composer run phpstan
      - name: PHPUnit
        run:  composer run phpunit
